registration_new:
    pattern:  /conference/registration
    defaults: { _controller: ZpiConferenceBundle:Registration:new }
    
conference_new:
    pattern:  /conference/new
    defaults: { _controller: ZpiConferenceBundle:Conference:new }
    
conference_show:
    pattern:  /conference/{id}
    defaults: { _controller: ZpiConferenceBundle:Conference:show }
    
