registration_new:
    pattern: /{_conf}/registration/new
    defaults: { _controller: ZpiConferenceBundle:Registration:new }
    
registration_list:
    pattern: /{_conf}/conference/registration/list
    defaults:  { _controller: ZpiConferenceBundle:Registration:list }
    
registration_show:
    pattern: /{_conf}/registration/{id}
    defaults: { _controller: ZpiConferenceBundle:Registration:show }
    requirements: 
          id: \d+
          
registration_user_show:
    pattern: /{_conf}/registration/show
    defaults: { _controller: ZpiConferenceBundle:Registration:show }
    requirements: 
          id: \d+
    
registration_delete:
    pattern: /{_conf}/conference/registration/delete/{id}
    defaults:  { _controller: ZpiConferenceBundle:Registration:delete }
    
registration_edit:
    pattern: /{_conf}/conference/registration/edit/{id}
    defaults: { _controller: ZpiConferenceBundle:Registration:edit }
    
registration_confirm:
    pattern: /{_conf}/registration/confirm
    defaults: { _controller: ZpiConferenceBundle:Registration:confirm }
    
data_diff:
    pattern: /{_conf}/registration/data_diff
    defaults: { _controller: ZpiConferenceBundle:Registration:dataDiff }
    
change_owner:
    pattern: /{_conf}/registration/{id}/paper/{paper_id}/changeOwner
    defaults: { _controller: ZpiConferenceBundle:Registration:changeOwner }
    requirements: 
          id: \d+
    
paper_delete:
    pattern: /{_conf}/conference/registration/{id}/paper/{paper_id}/delete
    defaults: { _controller: ZpiConferenceBundle:Registration:paperDelete }
    requirements: 
          id: \d+
    
conference_new:
    pattern: /{_conf}/conferences/new
    defaults: { _controller: ZpiConferenceBundle:Conference:new }
    
conference_edit:
    pattern: /{_conf}/edit
    defaults:  { _controller: ZpiConferenceBundle:Conference:edit }
    requirements:
        id: \d+

conference_list:
    pattern: /{_conf}/conferences
    defaults: { _controller: ZpiConferenceBundle:Conference:list }

conference_manage:
    pattern: /{_conf}/manage
    defaults: { _controller: ZpiConferenceBundle:Conference:manage }
    requirements:
        id: \d+
        
conference_manage_paper_details:
    pattern:  /{_conf}/manage/papers/{id}
    defaults: { _controller: ZpiPaperBundle:Paper:details }
    requirements:
        id: \d+
        
conference_manage_assign_editors:
    pattern:  /{_conf}/manage/assign_editors/{paper_id}
    defaults: { _controller: ZpiConferenceBundle:Conference:assignEditors }
    requirements:
        id: \d+
        paper_id: \d+
    
conference_manage_papers_deadline:
    pattern:  /{_conf}/manage/deadline/{paper_id}
    defaults: { _controller: ZpiConferenceBundle:Conference:deadline }
    requirements:
        id: \d+
        paper_id: \d+

conference_mail_to_all:
    pattern: /{_conf}/mail
    defaults: { _controller: ZpiConferenceBundle:Conference:mail }
    
