registration_new:
    pattern:  /conference/registration
    defaults: { _controller: ZpiConferenceBundle:Registration:new }
    
registration_list:
    pattern:  /conference/registration/list
    defaults:  { _controller: ZpiConferenceBundle:Registration:list }
    
registration_show:
    pattern:  /conference/registration/{id}
    defaults: { _controller: ZpiConferenceBundle:Registration:show }
    requirements: 
          id: \d+
    
registration_delete:
    pattern:  /conference/registration/delete/{id}
    defaults:  { _controller: ZpiConferenceBundle:Registration:delete }
    
registration_edit:
    pattern: /conference/registration/edit/{id}
    defaults: { _controller: ZpiConferenceBundle:Registration:edit }
    
paper_delete:
    pattern: /conference/registration/{id}/paperDelete/{paper_id}
    defaults: { _controller: ZpiConferenceBundle:Registration:paperDelete }
    requirements: 
          id: \d+
    
conference_new:
    pattern:  /conference/new
    defaults: { _controller: ZpiConferenceBundle:Conference:new }
    
conference_edit:
    pattern:  /conference/edit/{id}
    defaults:  { _controller: ZpiConferenceBundle:Conference:edit }
    requirements:
        id: \d+

conference_list:
    pattern:  /conference/list
    defaults: { _controller: ZpiConferenceBundle:Conference:list }

conference_manage:
    pattern:  /conference/manage/{id}
    defaults: { _controller: ZpiConferenceBundle:Conference:manage }
    requirements:
        id: \d+