# src/Zpi/ConferenceBundle/Resources/config/validation.yml
Zpi\ConferenceBundle\Entity\Conference:
    constraints:
        - Callback:
            methods:
                - [Zpi\ConferenceBundle\Validator\ConferenceValidator, isEndDateValid]                
                - [Zpi\ConferenceBundle\Validator\ConferenceValidator, isAbstractDeadlineValid]
                - [Zpi\ConferenceBundle\Validator\ConferenceValidator, isPaperDeadlineValid]
                - [Zpi\ConferenceBundle\Validator\ConferenceValidator, isCorrectedPaperDeadlineValid]               
                - [Zpi\ConferenceBundle\Validator\ConferenceValidator, isConfirmationDeadlineValid]
                - [Zpi\ConferenceBundle\Validator\ConferenceValidator, isbookingstartDateValid]
                - [Zpi\ConferenceBundle\Validator\ConferenceValidator, isbookingendDateValid]
                - [Zpi\ConferenceBundle\Validator\ConferenceValidator, isconferencebookPriceValid]
                
                         
    properties:
        name:          
            - NotBlank:
                message: "conf.violation.blank_value"
            - MinLength:
                limit: 5
                message: "conf.violation.min_name_length"
        prefix:          
            - NotBlank:
                message: "conf.violation.blank_value"
            - MinLength:
                limit: 3
                message: "conf.violation.min_prefix_length"

        minPageSize:
            - NotBlank:
                message: "conf.violation.blank_value"
            - Min:
                limit: 1
                message: "conf.violation.min_page_size"
        paperPrice:
            - NotBlank:
                message: "conf.violation.blank_value"
        extrapagePrice:
            - NotBlank:
                message: "conf.violation.blank_value"        
        conferencekitPrice:
            - NotBlank:
                message: "conf.violation.blank_value"
        onedayPrice:
            - NotBlank:
                message: "conf.violation.blank_value"
        address:
            - NotBlank:
                message: "conf.violation.blank_value"
            - Regex: "/^[A-Z][a-z]+\s[1-9][0-9]*$/"
              
        city:
            - NotBlank:
                message: "conf.violation.blank_value"
        postalCode:
            - NotBlank:
                message: "conf.violation.blank_value"
            - Regex:
                pattern: "/^[0-9]{2}[-][0-9]{3}$/"
                message: "conf.violation.postal_code"
        description:
            - NotBlank:
                message: "conf.violation.blank_value"
            - MaxLength:
                limit: 1000
                message: "conf.violation.description"
          
        
                
Zpi\ConferenceBundle\Entity\Registration:
    constraints:
       - Callback:
           methods:
               - [Zpi\ConferenceBundle\Validator\RegistrationValidator, isEndDateValid]
               - [Zpi\ConferenceBundle\Validator\RegistrationValidator, isStartDateValid]
               - [Zpi\ConferenceBundle\Validator\RegistrationValidator, arePapersValid]
               - [Zpi\ConferenceBundle\Validator\RegistrationValidator, arePaymentTypesValid]
               
    properties:
        type:
            - NotNull: ~
            
        declared:
            - "True": { message: "You should check this field, that you agree with the declaration above." }
            
                         
