# src/Zpi/ConferenceBundle/Resources/config/validation.yml
Zpi\ConferenceBundle\Entity\Conference:
    constraints:
        - Callback:
            methods:
                - [Zpi\ConferenceBundle\Validator\ConferenceValidator, isEndDateValid]
                - [Zpi\ConferenceBundle\Validator\ConferenceValidator, isDeadlineValid]
    properties:
        minPageSize:
            - Min:
                limit: 1
                message: "conf.violation.min_page_size"
        postalCode:
            - Regex:
                pattern: "/^[0-9]{2}[-][0-9]{3}$/"
                message: "conf.violation.postal_code"
        description:
            - MaxLength:
                limit: 1000
                message: "conf.violation.description.limit"
            