# przydałyby się requirementy dla slugów dla bezpieczeństwa, ale mi się nie chce tym bawić // @quba
paper_new:
    pattern:  /{_conf}/papers/new
    defaults: { _controller: ZpiPaperBundle:Paper:new }
    
papers_show:
    pattern:  /{_conf}/papers
    defaults: { _controller: ZpiPaperBundle:Paper:show }
    
paper_details:
    pattern:  /{_conf}/papers/{id}
    defaults: { _controller: ZpiPaperBundle:Paper:details }
    
document_upload:
    pattern:  /{_conf}/papers/{id}/upload
    defaults: { _controller: ZpiPaperBundle:Document:upload }
    
document_download:
    pattern:  /{_conf}/papers/document/get/{id}
    defaults: { _controller: ZpiPaperBundle:Document:download }
    
    
