# przydałyby się requirementy dla slugów dla bezpieczeństwa, ale mi się nie chce tym bawić // @quba
paper_new:
    pattern:  /{_conf}/paper/new
    defaults: { _controller: ZpiPaperBundle:Paper:new }
    
papers_list:
    pattern:  /{_conf}/papers
    defaults: { _controller: ZpiPaperBundle:Paper:list }

paper_edit:
    pattern:  /{_conf}/paper/edit/{id}
    defaults: { _controller: ZpiPaperBundle:Paper:edit }
   
paper_details:
    pattern:  /{_conf}/papers/{id}
    defaults: { _controller: ZpiPaperBundle:Paper:details }
    
document_upload:
    pattern:  /{_conf}/papers/{id}/upload
    defaults: { _controller: ZpiPaperBundle:Document:upload }
    
document_download:
    pattern:  /{_conf}/papers/document/get/{id}
    defaults: { _controller: ZpiPaperBundle:Document:download }
    
reviews_list:
    pattern:  /{_conf}/reviews
    defaults: { _controller: ZpiPaperBundle:Paper:list }
