paper_new:
    pattern:  /papers/new
    defaults: { _controller: ZpiPaperBundle:Paper:new }
    
papers_show:
    pattern:  /papers
    defaults: { _controller: ZpiPaperBundle:Paper:show }
    
paper_details:
    pattern:  /papers/{id}
    defaults: { _controller: ZpiPaperBundle:Paper:details }
    
document_upload:
    pattern:  /papers/{id}/upload
    defaults: { _controller: ZpiPaperBundle:Document:upload }
    
document_download:
    pattern:  /papers/document/get/{id}
    defaults: { _controller: ZpiPaperBundle:Document:download }
    
    
