# przydałyby się requirementy dla slugów dla bezpieczeństwa, ale mi się nie chce tym bawić // @quba
paper_new:
    pattern:  /{_conf}/paper/new
    defaults: { _controller: ZpiPaperBundle:Paper:new }
    
papers_list:
    pattern:  /{_conf}/papers
    defaults: { _controller: ZpiPaperBundle:Paper:list }

paper_edit:
    pattern:  /{_conf}/paper/edit/{id}
    defaults: { _controller: ZpiPaperBundle:Paper:edit }
    
change_paymenttype:
    pattern: /{_conf}/papers/changePaymentType
    defaults: { _controller: ZpiPaperBundle:Paper:changePaymentType }
   
paper_details:
    pattern:  /{_conf}/papers/{id}
    defaults: { _controller: ZpiPaperBundle:Paper:details }


    
document_upload:
    pattern:  /{_conf}/papers/{id}/upload
    defaults: { _controller: ZpiPaperBundle:Document:upload }
    
document_download:
    pattern:  /{_conf}/papers/document/get/{id}
    defaults: { _controller: ZpiPaperBundle:Document:download }
    
reviews_list:
    pattern:  /{_conf}/reviews
    defaults: { _controller: ZpiPaperBundle:Paper:list }

review_details:
    pattern:  /{_conf}/reviews/papers/{id}
    defaults: { _controller: ZpiPaperBundle:Paper:details }
    requirements:
        id: \d+

review_new:
    pattern:  /{_conf}/reviews/{doc_id}/new
    defaults: { _controller: ZpiPaperBundle:Review:new }
    requirements:
        doc_id: \d+

tech_review_new:
    pattern:  /{_conf}/reviews/{doc_id}/new_tech
    defaults: { _controller: ZpiPaperBundle:Review:new }
    requirements:
        doc_id: \d+

review_show:
    pattern:  /{_conf}/reviews/{doc_id}
    defaults: { _controller: ZpiPaperBundle:Review:show }
    requirements:
        doc_id: \d+

review_comment:
    pattern:  /{_conf}/comment/{doc_id}/{review_id}
    defaults: { _controller: ZpiPaperBundle:Review:comment, review_id: null }
    requirements:
        doc_id: \d+
        review_id:  \d+

review_comment_delete:
    pattern:  /{_conf}/reviews/comment/delete/{comment_id}
    defaults: { _controller: ZpiPaperBundle:Review:commentDelete }

review_comment_edit:
    pattern:  /{_conf}/reviews/comment/{comment_id}
    defaults: { _controller: ZpiPaperBundle:Review:commentEdit }
    
review_approve:
    pattern:  /{_conf}/reviews/approve/{doc_id}/{review_id}
    defaults: { _controller: ZpiPaperBundle:Review:approve, review_id: null }
    requirements:
        review_id: \d+
