homepage:
    pattern: /{_conf}/
    defaults: { _controller: ZpiPageBundle:Page:index }
    
subpage_new:
    pattern: /{_conf}/subpage/new
    defaults: { _controller: ZpiPageBundle:SubPage:new }
    
subpage_show:
    pattern: /{_conf}/subpage/{titleCanonical}
    defaults: { _controller: ZpiPageBundle:SubPage:show }
        
subpage_delete:
    pattern: /{_conf}/subpage/delete/{titleCanonical}
    defaults: { _controller: ZpiPageBundle:SubPage:delete }
    
subpage_update:
    pattern: /{_conf}/subpage/update/{titleCanonical}
    defaults: { _controller: ZpiPageBundle:SubPage:update }
