homepage:
    pattern:  /
    defaults: { _controller: ZpiPageBundle:Page:index }
    
subpage_new:
    pattern:  /subpage/new
    defaults: { _controller: ZpiPageBundle:SubPage:new }
    
subpage_show:
    pattern:  /subpage/{titleCanonical}
    defaults: { _controller: ZpiPageBundle:SubPage:show }
        
subpage_delete:
    pattern:   /subpage/delete/{titleCanonical}
    defaults: { _controller: ZpiPageBundle:SubPage:delete }
    
subpage_update:
    pattern:  /subpage/update/{titleCanonical}
    defaults: { _controller: ZpiPageBundle:SubPage:update }
