homepage:
    pattern:  /
    defaults: { _controller: ZpiPageBundle:Page:index }
    
subpage_new:
    pattern:  /subpage/new
    defaults: { _controller: ZpiPageBundle:SubPage:new }
    
subpage_show:
    pattern:  /subpage/{id}
    defaults: { _controller: ZpiPageBundle:SubPage:show }
