parameters:
#    zpi_page.example.class: Zpi\PageBundle\Example

services:
#    zpi_page.example:
#        class: %zpi_page.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
