fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /{_conf}/
    
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /{_conf}/profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /{_conf}/register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /{_conf}/resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /{_conf}/profile
    
emailval:
    pattern: /{_conf}/emailval
    defaults: { _controller: ZpiUserBundle:Registration:emailVal }
    
emailvalexist:
    pattern: /{_conf}/emailvalexist
    defaults: { _controller: ZpiUserBundle:Registration:emailValExist }

emailvalnonexist:
    pattern: /{_conf}/emailvalnonexist
    defaults: { _controller: ZpiUserBundle:Registration:emailValNonExist }
    
confirmacc:
    pattern: /{_conf}/confirmacc/{token}
    defaults: { _controller: ZpiUserBundle:Resetting:confirmAcc }