services:
    zpi_user.registration.form.type:
        class: Zpi\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: zpi_user_registration }
    zpi_user.profile.form.type:
        class: Zpi\UserBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: zpi_user_profile }