imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    translator:      { fallback: pl }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: en
        auto_start:     true


# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport:  gmail
    username:   zpimailer
    password:   isatmailer
#    delivery_address:  zpimailer@gmail.com
#    zeby nie spamowało nam skrzynek

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb'
    firewall_name: main
    user_class: Zpi\UserBundle\Entity\User
    registration:
        form:
            type: zpi_user_registration
            validation_groups:  [registration]
#        confirmation:       # włączymy w odpowiednim czasie
#            enabled: true
    profile:
        form:
            type: zpi_user_profile
            validation_groups: [profile]
services:
    bcc.twig.extension:
        class: BCC\ExtraToolsBundle\Twig\TwigExtension
        tags:
            -  { name: twig.extension }
    global:
        class: Zpi\PageBundle\Controller\OverallController
        
    kernel.listener.kernel_request:
        class: Zpi\PageBundle\Listener\Kernel
        arguments: ["@router", "@doctrine"]
        tags:
          - { name: kernel.event_listener, event: kernel.request , method: onKernelRequest }
        
    kernel.listener.kernel_controller:
        class: Zpi\PageBundle\Listener\Kernel
        arguments: ["@router", "@doctrine"]
        tags:
          - { name: kernel.event_listener, event: kernel.controller , method: onKernelController }
          
    messager:
        class: Zpi\UserBundle\Mailer\MessageManager
        arguments: ["@mailer", "@templating"]

parameters:
    security.http_utils.class: Zpi\PageBundle\Core\HttpUtils
    message_manager.class: Zpi\UserBundle\Mailer\MessageManager
    
twig:
    form:
        resources:
            - ':Form:default.html.twig'