security:
    providers:
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        main:
            pattern: .*
            form_login:
                provider: fos_userbundle
                check_path: fos_user_security_check
                login_path: fos_user_security_login
                default_target_path: homepage
            logout:
                path: fos_user_security_logout
                target: homepage
            anonymous:    true
# będzie trzeba te zezwolenia ogarnąć - tutaj tyle ile się da po całym url-u. Resztę w kontrolerach albo templatach ;)
    access_control:
        - { path: ^/.*/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/.*/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/.*/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/.*/papers, role: ROLE_USER }
        - { path: ^/.*/subpage/new, role: ROLE_USER }
        - { path: ^/.*/subpage/update, role: ROLE_USER }
        - { path: ^/.*/subpage/delete, role: ROLE_USER }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
#    acl:
#        connection: default
