security:
    providers:
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        main:
            pattern: .*
            form_login:
                provider: fos_userbundle
                check_path: fos_user_security_check
                login_path: fos_user_security_login
                default_target_path: homepage
            logout:
                path: fos_user_security_logout
                target: homepage
            anonymous:    true
# będzie trzeba te zezwolenia ogarnąć - tutaj tyle ile się da po całym url-u. Resztę w kontrolerach albo templatach ;)
    access_control:
        - { path: ^/.*/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/.*/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/.*/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/.*/papers, role: ROLE_USER }
        - { path: ^/.*/paper, role: ROLE_USER }
        - { path: ^/.*/registration, role: ROLE_USER }
        - { path: ^/.*/subpage/new, role: ROLE_USER }
        - { path: ^/.*/subpage/update, role: ROLE_USER }
        - { path: ^/.*/subpage/delete, role: ROLE_USER }
        - { path: ^/.*/conferences/, role: ROLE_ORGANIZER }

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        # Recenzent techniczny
        ROLE_TECHNICAL_REVIEWER: ROLE_USER
        # Recenzent zwykły (merytoryczny)
        ROLE_NORMAL_REVIEWER: ROLE_USER
        # Organizator
        ROLE_ORGANIZER: ROLE_USER
        # Póki co dziedziczy, bez tego użytkownik który miał dwie role: ROLE_ORGANIZER i ROLE_SUPERADMIN
        # nie miał dostępu do conferences. Ktoś mnie oświeci dlaczego? Rola superadmin obok organizer, nie pozwala?
        # @Gecaj
        ROLE_SUPER_ADMIN: ROLE_ADMIN, ROLE_ORGANIZER
#    acl:
#        connection: default
